name: auth
description: Authentication feature with login functionality and user session
  management for the admin application
publish_to: none
version: 0.0.1
homepage: null
resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^11.1.0
  domain:
    path: ../../core/domain
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.0
  freezed_annotation: ^3.0.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  shared: ^0.0.1

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  injectable_generator: ^2.12.0
  very_good_analysis: ^10.0.0

flutter: null
