name: admin_app
description: Admin dashboard web application - authenticated interface for managing CV content
publish_to: 'none'
version: 1.1.0+2
resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  admin_content: ^0.0.1
  auth: ^0.0.1
  auto_route: ^11.1.0
  data: ^0.0.1
  domain: ^0.0.1
  firebase_analytics: ^12.1.1
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  logger: ^2.5.0
  shared: ^0.0.1

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.12.0
  very_good_analysis: ^10.0.0

flutter:

  uses-material-design: true
